apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server-depl
spec:
  selector:
    matchLabels:
      app: json-server
  replicas: 1
  template:
    metadata:
      labels:
        app: json-server
    spec:
      containers:
      - name: json-server
        image: khuramzahid1991/json-server-image
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: json-server-service
spec:
  selector:
    app: json-server
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: json-server-url-cm
data:
  json-server-url: json-server-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-client-depl
spec:
  selector:
    matchLabels:
      app: react-client
  replicas: 1
  template:
    metadata:
      labels:
        app: react-client
    spec:
      containers:
      - name: react-client
        image: khuramzahid1991/react-client-image
        ports:
        - containerPort: 3000
        env:
        - name: JSON_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: json-server-url-cm
              key: json-server-url
        command: [ "sleep" ]
        args: [ "infinity" ]
---
apiVersion: v1
kind: Service
metadata:
  name: react-client-service
spec:
  selector:
    app: react-client
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30010