FROM node:12.20.0-alpine

WORKDIR /usr/src/app

COPY . .

RUN > ./src/baseUrl.js

RUN echo "export const baseUrl = \"http://localhost:3001\";" >> ./src/baseUrl.js

RUN npm install

EXPOSE 3000

CMD [ "npm", "start"]